import * as pb from 'protobufjs';
import * as tbadminAccount_pb from "rt_pb_generated/tbadmin/account_pb";
import * as tbadminAudit_pb from "rt_pb_generated/tbadmin/audit_pb";
import * as tbadminConfig_pb from "rt_pb_generated/tbadmin/config_pb";
import * as tbadminMatch_pb from "rt_pb_generated/tbadmin/match_pb";
import * as tbadminReport_pb from "rt_pb_generated/tbadmin/report_pb";
import * as tbadminShop_pb from "rt_pb_generated/tbadmin/shop_pb";
import * as tbadminStats_pb from "rt_pb_generated/tbadmin/stats_pb";
import * as tbmatchAccount_pb from "rt_pb_generated/tbmatch/account_pb";
import * as tbmatchCrash_pb from "rt_pb_generated/tbmatch/crash_pb";
import * as tbmatchEvent_pb from "rt_pb_generated/tbmatch/event_pb";
import * as tbmatchLobby_pb from "rt_pb_generated/tbmatch/lobby_pb";
import * as tbmatchLog_pb from "rt_pb_generated/tbmatch/log_pb";
import * as tbmatchMatch_pb from "rt_pb_generated/tbmatch/match_pb";
import * as tbmatchQuery_pb from "rt_pb_generated/tbmatch/query_pb";
import * as tbmatchSession_pb from "rt_pb_generated/tbmatch/session_pb";
import * as tbmatchShop_pb from "rt_pb_generated/tbmatch/shop_pb";
import * as tbmatchUser_pb from "rt_pb_generated/tbmatch/user_pb";
import * as tbportalPortal_pb from "rt_pb_generated/tbportal/portal_pb";
import * as tbrpcTbrpc from "rt_pb_generated/tbrpc/tbrpc_pb";
import * as tbui from "rt_pb_generated/tbui/tbcharacter_pb";

const ProtoFiles = {
    Messages: {
        Empty: tbrpcTbrpc.Empty,
        Result: tbrpcTbrpc.Result,
        PingTestResult: tbmatchMatch_pb.PingTestResult,
        GameEndpointConfig: tbmatchMatch_pb.GameEndpointConfig,
        NetworkAddr: tbmatchMatch_pb.NetworkAddr,
        LoginRequest: tbmatchSession_pb.LoginRequest,
        GetGameSessionTicketRequest: tbmatchSession_pb.GetGameSessionTicketRequest,
        GetGameSessionTicketResult: tbmatchSession_pb.GetGameSessionTicketResult,
        RedeemGameSessionTicketRequest: tbmatchSession_pb.RedeemGameSessionTicketRequest,
        GetMatchRequest: tbmatchMatch_pb.GetMatchRequest,
        CreateLobbyRequest: tbmatchLobby_pb.CreateLobbyRequest,
        GetLobbyJoinCodeRequest: tbmatchLobby_pb.GetLobbyJoinCodeRequest,
        GetEventResult: tbmatchEvent_pb.GetEventResult,
        Event: Event,
        GetEventRequest: tbmatchEvent_pb.GetEventRequest,
        PingTestCompleteEvent: tbmatchEvent_pb.PingTestCompleteEvent,
        GameProfile: tbmatchMatch_pb.GameProfile,
        PlayerStats: tbmatchMatch_pb.PlayerStats,
        CharacterStats: tbmatchMatch_pb.CharacterStats,
        PlayerPreferences: tbmatchMatch_pb.PlayerPreferences,
        ClientFeatureSet: tbmatchMatch_pb.ClientFeatureSet,
        FeatureValue: tbmatchMatch_pb.FeatureValue,
        MatchCreatedEvent: tbmatchEvent_pb.MatchCreatedEvent,
        Player: tbmatchMatch_pb.PlayerPreferences,
        GameConfig: tbmatchMatch_pb.GameConfig,
        GameOptions: tbmatchMatch_pb.GameOptions,
        CharacterSpec: tbmatchMatch_pb.CharacterSpec,
        VariantSpec: tbmatchMatch_pb.VariantSpec,
        LocMsg: tbrpcTbrpc.LocMsg,
        MsgParam: tbrpcTbrpc.MsgParam,
        GameSessionRequest: tbportalPortal_pb.GameSessionRequest,
        ClientSpec: tbportalPortal_pb.ClientSpec,
        FilterChangedEvent: tbmatchEvent_pb.FilterChangedEvent,
        WaitMatchProgressEvent: tbmatchEvent_pb.WaitMatchProgressEvent,
        MatchOutcomeEvent: tbmatchEvent_pb.MatchOutcomeEvent,
        MatchResult: tbmatchMatch_pb.MatchResult,
        MatchExperience: tbmatchMatch_pb.MatchExperience,
        MatchAbandonedEvent: tbmatchEvent_pb.MatchAbandonedEvent,
        MatchConnectedEvent: tbmatchEvent_pb.MatchConnectedEvent,
        MatchOverEvent: tbmatchEvent_pb.MatchOverEvent,
        NextGameConfig: tbmatchMatch_pb.NextGameConfig,
        GameBeginEvent: tbmatchEvent_pb.GameBeginEvent,
        GameInputEvent: tbmatchEvent_pb.GameInputEvent,
        GameOverEvent: tbmatchEvent_pb.GameOverEvent,
        GameReport: tbmatchMatch_pb.GameReport,
        UserCheckNetworkEvent: tbmatchEvent_pb.UserCheckNetworkEvent,
        UserSessionClosedEvent: tbmatchEvent_pb.UserSessionClosedEvent,
        LobbyJoinEvent: tbmatchEvent_pb.LobbyJoinEvent,
        LobbyLeaveEvent: tbmatchEvent_pb.LobbyLeaveEvent,
        LobbyUpdateEvent: tbmatchEvent_pb.LobbyUpdateEvent,
        LobbyMatchStartEvent: tbmatchEvent_pb.LobbyMatchStartEvent,
        Lobby: tbmatchLobby_pb.Lobby,
        LobbyMember: tbmatchLobby_pb.LobbyMember,
        TrainingGameOptions: tbmatchMatch_pb.TrainingGameOptions,
        EventQueue: tbportalPortal_pb.EventQueue,
        UserInfo: tbmatchAccount_pb.UserInfo,
        UserAccountSpec: tbmatchAccount_pb.UserAccountSpec,
        ContactAddress: tbmatchAccount_pb.ContactAddress,
        UserPrefs: tbmatchAccount_pb.UserPrefs,
        SearchUsersResult: tbadminAccount_pb.SearchUsersResult,
        CreateUserResult: tbadminAccount_pb.CreateUserResult,
        NukeHandleResult: tbadminAccount_pb.NukeHandleResult,
        GetHandleHistoryResult: tbadminAccount_pb.GetHandleHistoryResult,
        HandleChange: tbadminAccount_pb.HandleChange,
        SearchAuditHistoryResult: tbadminAudit_pb.SearchAuditHistoryResult,
        AuditEvent: tbadminAudit_pb.AuditEvent,
        AccountSummary: tbadminAudit_pb.AccountSummary,
        AuditAccount: tbadminAudit_pb.AuditAccount,
        AuditOrder: tbadminAudit_pb.AuditOrder,
        AppConfig: tbadminConfig_pb.AppConfig,
        AccountConfig: tbadminConfig_pb.AccountConfig,
        MatchServiceConfig: tbadminConfig_pb.MatchServiceConfig,
        RankConfig: tbadminConfig_pb.RankConfig,
        Glicko2RatingConfig: tbadminConfig_pb.Glicko2RatingConfig,
        LevelProgression: tbadminConfig_pb.LevelProgression,
        EchelonConfig: tbadminConfig_pb.EchelonConfig,
        EchelonRules: tbadminConfig_pb.EchelonRules,
        ShopConfig: tbadminConfig_pb.ShopConfig,
        PaymentConfig: tbadminConfig_pb.PaymentConfig,
        CurrencyConfig: tbadminConfig_pb.CurrencyConfig,
        CurrencyDesc: tbadminConfig_pb.CurrencyDesc,
        Money: tbrpcTbrpc.Money,
        EventConfig: tbadminConfig_pb.EventConfig,
        AuditConfig: tbadminConfig_pb.AuditConfig,
        LobbyServiceConfig: tbadminConfig_pb.LobbyServiceConfig,
        CrashReportConfig: tbadminConfig_pb.CrashReportConfig,
        ServerRolloutFlags: tbadminConfig_pb.ServerRolloutFlags,
        DesyncReportConfig: tbadminConfig_pb.DesyncReportConfig,
        ExportTrimConfig: tbadminConfig_pb.ExportTrimConfig,
        GetGlobalConfigResult: tbadminConfig_pb.GetGlobalConfigResult,
        GlobalConfig: tbadminConfig_pb.GlobalConfig,
        GetMatchQueueConfigResult: tbadminConfig_pb.GetMatchQueueConfigResult,
        MatchQueueConfig: tbadminConfig_pb.MatchQueueConfig,
        GetMatchUserConfigResult: tbadminConfig_pb.GetMatchUserConfigResult,
        MatchUserConfig: tbadminConfig_pb.MatchUserConfig,
        GetLobbyConfigResult: tbadminConfig_pb.GetLobbyConfigResult,
        LobbyConfig: tbadminConfig_pb.LobbyConfig,
        ListFeatureDefinitionsResult: tbadminConfig_pb.ListFeatureDefinitionsResult,
        FeatureDefinition: tbadminConfig_pb.FeatureDefinition,
        ListFeatureRulesResult: tbadminConfig_pb.ListFeatureRulesResult,
        FeatureRule: tbadminConfig_pb.FeatureRule,
        GetActiveFeaturesResult: tbadminConfig_pb.GetActiveFeaturesResult,
        GetMatchQueueUsersResult: tbadminMatch_pb.GetMatchQueueUsersResult,
        QueueUser: tbadminMatch_pb.QueueUser,
        GetLobbiesResult: tbadminMatch_pb.GetLobbiesResult,
        LobbySummary: tbadminMatch_pb.LobbySummary,
        GetLobbyResult: tbadminMatch_pb.GetLobbyResult,
        GetActiveMatchesResult: tbadminMatch_pb.GetActiveMatchesResult,
        ActiveMatch: tbadminMatch_pb.ActiveMatch,
        GameDescriptor: tbmatchMatch_pb.GameDescriptor,
        GetActiveMatchResult: tbadminMatch_pb.GetActiveMatchResult,
        GetRecentMatchesResult: tbadminMatch_pb.GetRecentMatchesResult,
        RecentMatch: tbadminMatch_pb.RecentMatch,
        GetMatchDetailResult: tbadminMatch_pb.GetMatchDetailResult,
        GetPlayerDetailResult: tbadminMatch_pb.GetPlayerDetailResult,
        MatchPlayer: tbadminMatch_pb.MatchPlayer,
        ListDesyncsResult: tbadminReport_pb.ListDesyncsResult,
        DesyncReportHeader: tbmatchMatch_pb.DesyncReportHeader,
        ListCrashesResult: tbadminReport_pb.ListCrashesResult,
        CrashCollection: tbadminReport_pb.CrashCollection,
        CrashReportHeader: tbadminReport_pb.CrashReportHeader,
        ListCrashBuildIdentifiersResult: tbadminReport_pb.ListCrashBuildIdentifiersResult,
        CrashBuildIdentifier: tbadminReport_pb.CrashBuildIdentifier,
        ListCrashCollectionsResult: tbadminReport_pb.ListCrashCollectionsResult,
        SearchPurchaseOrdersResult: tbadminShop_pb.SearchPurchaseOrdersResult,
        PurchaseOrder: tbmatchShop_pb.PurchaseOrder,
        PurchaseOrderItem: tbmatchShop_pb.PurchaseOrderItem,
        PaymentMethod: tbmatchShop_pb.PaymentMethod,
        BillingAddress: tbmatchShop_pb.BillingAddress,
        Transaction: tbmatchShop_pb.Transaction,
        UserCountStats: tbadminStats_pb.UserCountStats,
        GetSessionsResult: tbadminStats_pb.GetSessionsResult,
        Session: tbadminStats_pb.Session,
        GetCharacterUsageResult: tbadminStats_pb.GetCharacterUsageResult,
        CharacterUsageReport: tbadminStats_pb.CharacterUsageReport,
        CharacterReportOptions: tbadminStats_pb.CharacterReportOptions,
        CharacterUsage: tbadminStats_pb.CharacterUsage,
        RatingWinRatioReport: tbadminStats_pb.RatingWinRatioReport,
        Matchup: tbadminStats_pb.Matchup,
        GetSecretQuestionResult: tbmatchAccount_pb.GetSecretQuestionResult,
        GetLobbyJoinCodeResult: tbmatchLobby_pb.GetLobbyJoinCodeResult,
        GetGameReplayRecordResult: tbmatchMatch_pb.GetGameReplayRecordResult,
        GameReplayRecord: tbmatchMatch_pb.GameReplayRecord,
        InputRecord: tbmatchMatch_pb.InputRecord,
        GetPlayerStatsResult: tbmatchMatch_pb.GetPlayerStatsResult,
        GetRecentGamesResult: tbmatchMatch_pb.GetRecentGamesResult,
        GameRecord: tbmatchMatch_pb.GameRecord,
        GetStoredPaymentMethodsResult: tbmatchShop_pb.GetStoredPaymentMethodsResult,
        SubmitPurchaseOrderResult: tbmatchShop_pb.SubmitPurchaseOrderResult,
        GetAccountOrderHistoryResult: tbmatchShop_pb.GetAccountOrderHistoryResult,
        GetAccountBalanceHistoryResult: tbmatchShop_pb.GetAccountBalanceHistoryResult,
        BalanceEntry: tbmatchShop_pb.BalanceEntry,
        GetAccountBalanceResult: tbmatchShop_pb.GetAccountBalanceResult,
    },
    Enums: {
        Status: tbrpcTbrpc.Status,
        GameType: tbmatchSession_pb.GameType,
        LobbyType: tbmatchLobby_pb.LobbyType,
        MatchType: tbmatchMatch_pb.MatchType,
        SkillEstimateType: tbmatchMatch_pb.SkillEstimateType,
        MatchOutcome: tbmatchMatch_pb.MatchOutcome,
        LobbyState: tbmatchLobby_pb.LobbyState,
        MeterRefillType: tbmatchMatch_pb.MeterRefillType,
        LoginStatus: tbmatchAccount_pb.LoginStatus,
        AuditEventType: tbadminAudit_pb.AuditEventType,
        OrderStatus: tbmatchShop_pb.OrderStatus,
        Access: tbrpcTbrpc.Access,
    }
}
var x = new ProtoFiles.Messages.Empty();
var y = new ProtoFiles.Messages.LoginRequest();